### ISSUE TITLE
Wipe data structures using finalizers

### ISSUE THREAD

**Issue by juniorz** [coyim/otr3#51]
We are wiping data structures at the moment we reassign them, but we could use finalizers instead.

**Comment by olabini** [comment]
I don't think we should - we have no control over when finalizers run and they are not guaranteed to run at all. So I would suggest not.

**Comment by juniorz** [comment]
Fair enough. I'm worried about conversation not having a `Wipe()` and the only moment the keys are wiped is when you rotate them. The last keys won't be wiped when conversation is garbage collected.

**Comment by olabini** [comment]
Yeah, that's a problem. But same problem as last mac keys not being revealed if you don't end the convo, right?

**Comment by olabini** [comment]
Closing this.
