### ISSUE TITLE
libotr 4.1.1 ?

### ISSUE THREAD

**Issue by Neustradamus** [coyim/otr3#54]
It is based on libotr 4.1.1 or 4.1.0?

The website is https://www.otr.im/

Last version 4.1.1 : https://bugs.otr.im/lib/libotr

Time to go:
- https://github.com/otrv4
- https://github.com/otrv4/libotr-ng

**Comment by olabini** [comment]
Hi,

This OTR library is a Go-lang implementation of the OTR protocol, version 3. It's not based on the C library at all.

And, yes - we are aware of the OTRv4 efforts - since we are the ones developing OTRv4.
