### ISSUE TITLE
Do security audit

### ISSUE THREAD

**Issue by olabini** [coyim/otr3#56]
The otr3 Golang implementation is now stable enough that it makes sense to commission a security audit of the code to make sure it works as intended and doesn't have any unexpected problems.

CAD has some funds for this audit, which will make it possible to commission a firm to help with this.

I will proceed by asking for proposals from two or three firms.

**Comment by olabini** [comment]
I have reached out to two firms and asked for proposals and quotes.

**Comment by claucece** [comment]
This is currently being done.

**Comment by claucece** [comment]
We have the draft of the report, and the final one will be submitted by the end of August.

**Comment by claucece** [comment]
The security audit is done!
